# -*- coding: utf-8 -*-
"""Q1Labtraintestval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C-WM5sCcXsFvMA8UpuiKWUVSbKJhpJjy
"""

import pandas as pd
from google.colab import files

import sklearn
from sklearn.model_selection import train_test_split
path = '/content/drive/MyDrive/ML 1/Q1 Lab/'
attribute = "SymmetricalUncertAttributeEval/"
dataset = pd.read_csv(path + attribute + "dataset.csv")

trainSet, tempSet = train_test_split(dataset, test_size=0.3, random_state=42)
valSet, testSet = train_test_split(tempSet, test_size=0.5, random_state=42)

trainSet.to_csv(path + attribute +'trainSet.csv', index = False)
testSet.to_csv(path + attribute + 'testSet.csv', index = False)
valSet.to_csv(path + attribute + 'valSet.csv', index = False)

import pandas as pd
import numpy as np
data = pd.read_csv('/content/drive/MyDrive/ML 1/Q1 Lab/newData.csv')
data['Weapon Used Cd'] = pd.to_numeric(data["'Weapon Used Cd'"], errors='coerce')
median_value = data["Weapon Used Cd"].median()
print(median_value)

import pandas as pd
import numpy as np

dataset = pd.read_csv("/content/drive/MyDrive/ML 1/Q1 Lab/cleanData.csv")

last_column = dataset.columns[-1]
bins = 10
bin_labels = range(1, bins+1)
dataset[last_column] = pd.cut(dataset[last_column], bins=bins, labels=bin_labels)
output_file = "/content/drive/MyDrive/ML 1/Q1 Lab/newData_binned.csv"
dataset.to_csv(output_file, index=False)

import pandas as pd

dataset = pd.read_csv("/content/drive/MyDrive/ML 1/Q1 Lab/cleanData.csv")


age_column = dataset.iloc[:, 4]

valid_ages = age_column[age_column > 0]
median_age = int(valid_ages.median())

dataset.iloc[:, 4] = age_column.apply(lambda age: median_age if age <= 0 else age)

dataset.iloc[:, 4] = dataset.iloc[:, 4].astype(int)

dataset.to_csv("/content/drive/MyDrive/ML 1/Q1 Lab/cleanData.csv", index=False)

import pandas as pd

dataset = pd.read_csv("/content/drive/MyDrive/ML 1/Q1 Lab/cleanData.csv")

column_name = dataset.columns[5]

valid_genders = dataset[dataset[column_name].isin(['F', 'M'])]

mode_gender = valid_genders[column_name].mode()[0]

dataset[column_name] = dataset[column_name].replace({'H': mode_gender, 'X': mode_gender})

dataset.to_csv("/content/drive/MyDrive/ML 1/Q1 Lab/cleanData.csv", index=False)

import pandas as pd
from statistics import mode

dataset = pd.read_csv("/content/drive/MyDrive/ML 1/Q1 Lab/cleanData.csv")

ethnicity_column = dataset.iloc[:, 6]
non_missing_ethnicities = ethnicity_column[ethnicity_column != 'X']

mode_ethnicity = mode(non_missing_ethnicities)

dataset.iloc[:, 6] = dataset.iloc[:, 6].replace('X', mode_ethnicity)

dataset.to_csv("/content/drive/MyDrive/ML 1/Q1 Lab/cleanData.csv", index=False)
